set(CPACK_GENERATOR "NSIS")
set(CPACK_PACKAGE_VENDOR "${SOLARUSLAUNCHER_ORGANISATION}")
set(CPACK_NSIS_DISPLAY_NAME "${PROJECT_NAME}")
set(CPACK_NSIS_PACKAGE_NAME "${PROJECT_NAME} Installer")
set(CPACK_NSIS_EXECUTABLES_DIRECTORY ".")
set(CPACK_NSIS_MUI_ICON "${CMAKE_SOURCE_DIR}/cmake/cpack/NSIS/NSISInstallerIcon.ico")
set(CPACK_NSIS_MUI_UNICON "${CPACK_NSIS_MUI_ICON}")
set(CPACK_NSIS_INSTALLED_ICON_NAME "${CPACK_NSIS_MUI_ICON}")
set(CPACK_NSIS_HELP_LINK "${LINKS_HELP}")
set(CPACK_NSIS_URL_INFO_ABOUT "${PROJECT_HOMEPAGE_URL}")
set(CPACK_NSIS_CONTACT "${LINKS_CONTACT}")

# TODO: It seems that MUI on Msys2 needs windows native paths, but the images are not shown...
file(TO_NATIVE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/cpack/NSIS/NSISWelcomeImage.bmp" CPACK_NSIS_MUI_WELCOMEFINISHPAGE_BITMAP)
set(CPACK_NSIS_MUI_UNWELCOMEFINISHPAGE_BITMAP "${CPACK_NSIS_MUI_WELCOMEFINISHPAGE_BITMAP}")
file(TO_NATIVE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/cpack/NSIS/NSISHeaderImage.bmp" CPACK_NSIS_MUI_HEADERIMAGE)

# set(CPACK_NSIS_MUI_HEADERIMAGE "${CMAKE_SOURCE_DIR}/cmake/cpack/NSIS/NSISHeaderImage.bmp")

set(CPACK_NSIS_COMPRESSOR "/SOLID /FINAL lzma")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_NSIS_MODIFY_PATH OFF)
set(CPACK_NSIS_MANIFEST_DPI_AWARE ON)
set(CPACK_NSIS_BRANDING_TEXT "v${PROJECT_VERSION}")
set(CPACK_NSIS_IGNORE_LICENSE_PAGE ON)
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES\\\\${SOLARUSLAUNCHER_ORGANISATION}")

# Set the file extension for the document type.
# set(SOLARUSLAUNCHER_EXECUTABLE_NAME "$<TARGET_FILE_NAME:${PROJECT_NAME}>")
# set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "
#   WriteRegStr HKCR \".${FILE_EXTENSION}\" \"\" \"${SOLARUSLAUNCHER_DOCUMENT_IDENTIFIER}\"
#   WriteRegStr HKCR \"${SOLARUSLAUNCHER_DOCUMENT_IDENTIFIER}\" \"\" \"${SOLARUSLAUNCHER_DOCUMENT_NAME}\"
#   WriteRegStr HKCR \"${SOLARUSLAUNCHER_DOCUMENT_IDENTIFIER}\\DefaultIcon\" \"\" \"$INSTDIR\\${SOLARUSLAUNCHER_EXECUTABLE_NAME},1\"
#   WriteRegStr HKCR \"${SOLARUSLAUNCHER_DOCUMENT_IDENTIFIER}\\shell\\open\\command\" \"\" \"$INSTDIR\\${SOLARUSLAUNCHER_EXECUTABLE_NAME} \\\"%1\\\"\"
#   DetailPrint \"Registry modified: file association added\"
# ")
# set(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "
#   DeleteRegKey HKCR \".${FILE_EXTENSION}\"
#   DeleteRegKey HKCR \"${SOLARUSLAUNCHER_DOCUMENT_IDENTIFIER}\"
# ")

# Components.
set(CPACK_COMPONENTS_ALL ${PROJECT_NAME})
