string(TIMESTAMP PROJECT_BUILD_YEAR "%Y")
set(DISPLAY_NAME "Solarus Launcher")
set(EXECUTABLE_NAME "solarus-launcher")
set(APP_COPYRIGHT "© 2006-${PROJECT_BUILD_YEAR} Solarus Labs.")
set(APP_IDENTIFIER "org.solarus-games.solarus-launcher")
set(APP_GLOBAL_PROJECT "Solarus")
set(APP_ORGANISATION "Solarus Labs")
set(APP_ORGANISATION_DOMAIN "solarus-games.org")
set(APP_LICENSE "GPL-3.0 and CC-BY-SA-4.0") # Should be SPDX identifiers.
set(APP_TRADEMARKS "Licensed under ${APP_LICENSE}")
set(APP_EMAIL "solarus-labs@solarus-games.org")
set(LINKS_X "https://x.com/solarusgames")
set(LINKS_MASTODON "https://mastodon.gamedev.place/@solarus")
set(LINKS_YOUTUBE "https://www.youtube.com/c/ChristophoZS")
set(LINKS_DISCORD "https://discord.gg/yYHjJHt")
set(LINKS_SOURCE_CODE "https://www.gitlab.com/solarus-games/solarus")
set(LINKS_BUGTRACKER "https://www.gitlab.com/solarus-games/solarus-launcher/-/issues")
set(LINKS_CONTACT "https://www.solarus-games.org/about/contact")
set(LINKS_RELEASES "https://gitlab.com/api/v4/projects/solarus-games%2Fsolarus-launcher-legacy/releases")
set(LINKS_UPDATE_ENDPOINT "https://gitlab.com/api/v4/projects/solarus-games%2Fsolarus-launcher-legacy/releases/permalink/latest")
set(LINKS_HELP "https://docs.solarus-games.org")
set(LINKS_DONATION "https://www.solarus-games.org/about/donate/")

set(DOCUMENT_NAME "Solarus Quest")
set(DOCUMENT_EXTENSION "solarus")
set(DOCUMENT_TYPE_IDENTIFIER "org.solarus-games.solarus-quest")
