string(TIMESTAMP PROJECT_BUILD_YEAR "%Y")
set(SOLARUSLAUNCHER_DISPLAY_NAME "Solarus Launcher")
set(SOLARUSLAUNCHER_EXECUTABLE_NAME "${PROJECT_NAME}")
set(SOLARUSLAUNCHER_COPYRIGHT "© 2006-${PROJECT_BUILD_YEAR} Solarus Labs.")
set(SOLARUSLAUNCHER_APP_IDENTIFIER "org.solarus-games.solarus-launcher")
set(SOLARUSLAUNCHER_ORGANISATION "Solarus Labs")
set(SOLARUSLAUNCHER_ORGANISATION_DOMAIN "solarus-games.org")
set(SOLARUSLAUNCHER_LICENSE "GPL-3.0 and CC-BY-SA-4.0") # Should be SPDX identifiers.
set(SOLARUSLAUNCHER_TRADEMARKS "Licensed under ${SOLARUSLAUNCHER_LICENSE}")
set(SOLARUSLAUNCHER_EMAIL "solarus-labs@solarus-games.org")
set(LINKS_X "https://x.com/solarusgames")
set(LINKS_MASTODON "https://mastodon.gamedev.place/@solarus")
set(LINKS_YOUTUBE "https://www.youtube.com/c/ChristophoZS")
set(LINKS_DISCORD "https://discord.gg/yYHjJHt")
set(LINKS_SOURCE_CODE "https://www.gitlab.com/solarus-games/solarus")
set(LINKS_BUGTRACKER "https://www.gitlab.com/solarus-games/solarus-launcher/-/issues")
set(LINKS_CONTACT "https://www.solarus-games.org/about/contact")
set(LINKS_RELEASES "https://gitlab.com/api/v4/projects/solarus-games%2Fsolarus-launcher-legacy/releases")
set(LINKS_UPDATE_ENDPOINT "https://gitlab.com/api/v4/projects/solarus-games%2Fsolarus-launcher-legacy/releases/permalink/latest")
set(LINKS_HELP "https://docs.solarus-games.org")
set(LINKS_DONATION "https://www.solarus-games.org/about/donate/")

set(SOLARUSLAUNCHER_DOCUMENT_NAME "Solarus Quest")
set(SOLARUSLAUNCHER_DOCUMENT_EXTENSION "solarus")
set(SOLARUSLAUNCHER_TYPE_IDENTIFIER "org.solarus-games.solarus-quest")
