# Set files to install
install(TARGETS solarus-editor
  RUNTIME DESTINATION ${SOLARUS_INSTALL_BINDIR}
)

if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  set(MACOS_BUNDLE_RESOURCES_DIR $<TARGET_FILE_NAME:${PROJECT_NAME}>.app/Contents/Resources)

  # macOS app bundle.
  install(DIRECTORY ${CMAKE_SOURCE_DIR}/assets
    DESTINATION ${MACOS_BUNDLE_RESOURCES_DIR}
    COMPONENT ${PROJECT_NAME}
    PATTERN ".DS_Store" EXCLUDE
  )

  install(FILES ${SOLARUSEDITOR_TRANSLATIONS_QM}
    DESTINATION ${MACOS_BUNDLE_RESOURCES_DIR}/translations
    COMPONENT ${PROJECT_NAME}
  )
else()
  # Other platforms.
  install(DIRECTORY ${CMAKE_SOURCE_DIR}/assets
    DESTINATION ${SOLARUS_INSTALL_DATADIR}
    COMPONENT ${PROJECT_NAME}
    PATTERN ".DS_Store" EXCLUDE
  )

  install(FILES ${SOLARUSEDITOR_TRANSLATIONS_QM}
    DESTINATION "${SOLARUS_INSTALL_DATADIR}/translations"
    COMPONENT ${PROJECT_NAME} 
  )
endif()
