set(DMG_SCRIPT ON CACHE BOOL "Enable DMG customization with AppleScript")

set(BUNDLE_NAME "${DISPLAY_NAME}.app")
if(DMG_SCRIPT)
  set(DMG_APPLESCRIPT "${CMAKE_CURRENT_BINARY_DIR}/DMGSetup.applescript")
  configure_file(
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/cpack/DragNDrop/DMGSetup.applescript.in
    ${DMG_APPLESCRIPT}
    @ONLY
  )
endif()

set(CPACK_GENERATOR "DragNDrop")
set(CPACK_PACKAGE_VENDOR "${APP_ORGANISATION}")
set(CPACK_PACKAGE_FILE_NAME "${DISPLAY_NAME} Installer")
set(CPACK_PACKAGE_ICON "${CMAKE_CURRENT_SOURCE_DIR}/cmake/cpack/DragNDrop/DMGVolumeIcon.icns")
set(CPACK_BUNDLE_NAME "${DISPLAY_NAME}")
set(CPACK_DMG_VOLUME_NAME "${DISPLAY_NAME} Installer")
set(CPACK_DMG_BACKGROUND_IMAGE "${CMAKE_CURRENT_SOURCE_DIR}/cmake/cpack/DragNDrop/DMGBackground@2x.png")
if(DMG_APPLESCRIPT)
  set(CPACK_DMG_DS_STORE_SETUP_SCRIPT "${DMG_APPLESCRIPT}")
endif()
set(CPACK_INSTALL_CMAKE_PROJECTS "${CMAKE_CURRENT_BINARY_DIR};${PROJECT_NAME};${PROJECT_NAME};/")
# Components.
set(CPACK_COMPONENTS_ALL ${PROJECT_NAME})
