set(CMAKE_MACOSX_RPATH ON)
set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)

# Add the bundle icon to the macOS bundle.
set(SOLARUSLAUNCHER_MACOS_BUNDLE_ICON_FILE "solarus_launcher_icon.icns")
set(SOLARUSLAUNCHER_MACOS_APP_ICON "${CMAKE_CURRENT_SOURCE_DIR}/resources/app_icon/${SOLARUSLAUNCHER_MACOS_BUNDLE_ICON_FILE}")
set_source_files_properties(${SOLARUSLAUNCHER_MACOS_APP_ICON} PROPERTIES MACOSX_PACKAGE_LOCATION "Resources")

set(SOLARUSLAUNCHER_MACOS_DOCUMENT_ICON_FILE "macos_doc_icon.icns")
set(SOLARUSLAUNCHER_MACOS_DOCUMENT_ICON "${CMAKE_CURRENT_SOURCE_DIR}/resources/doc_icon/macos/${SOLARUSLAUNCHER_MACOS_DOCUMENT_ICON_FILE}")
set_source_files_properties(${SOLARUSLAUNCHER_MACOS_DOCUMENT_ICON} PROPERTIES MACOSX_PACKAGE_LOCATION "Resources")

target_sources(${PROJECT_NAME} PRIVATE
  ${SOLARUSLAUNCHER_MACOS_APP_ICON}
  ${SOLARUSLAUNCHER_MACOS_DOCUMENT_ICON}
)

# macOS-specific settings.
set_target_properties(${PROJECT_NAME} PROPERTIES
  OUTPUT_NAME ${SOLARUSLAUNCHER_DISPLAY_NAME} # To get a pretty name in  macOS Launchpad.
  MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
  MACOSX_BUNDLE_BUNDLE_NAME ${SOLARUSLAUNCHER_DISPLAY_NAME}
  MACOSX_BUNDLE_EXECUTABLE_NAME ${SOLARUSLAUNCHER_EXECUTABLE_NAME}
  MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
  MACOSX_BUNDLE_GUI_IDENTIFIER ${SOLARUSLAUNCHER_APP_IDENTIFIER}
  MACOSX_BUNDLE_COPYRIGHT ${SOLARUSLAUNCHER_COPYRIGHT}
  MACOSX_BUNDLE_ICON_FILE ${SOLARUSLAUNCHER_MACOS_BUNDLE_ICON_FILE}
  MACOSX_BUNDLE TRUE
  XCODE_ATTRIBUTE_EXECUTABLE_NAME ${SOLARUSLAUNCHER_EXECUTABLE_NAME}
  XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED OFF
  XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY ""
  XCODE_ATTRIBUTE_CODE_SIGN_STYLE "Manual"
  XCODE_ATTRIBUTE_CODE_SIGN_INJECT_BASE_ENTITLEMENTS OFF
  XCODE_ATTRIBUTE_OTHER_CODE_SIGN_FLAGS ""
)

set(SOLARUSLAUNCHER_EXECUTABLE_NAME ${SOLARUSLAUNCHER_DISPLAY_NAME})

# Add Info.plist to the macOS bundle only on macOS.
set(SOLARUSLAUNCHER_MACOS_BUNDLE_PLIST "${CMAKE_CURRENT_BINARY_DIR}/Info.plist")
configure_file(
  "${CMAKE_CURRENT_SOURCE_DIR}/cmake/macOS/Info.plist.in"
  "${SOLARUSLAUNCHER_MACOS_BUNDLE_PLIST}"
  @ONLY
)
target_sources(${PROJECT_NAME} PRIVATE "${SOLARUSLAUNCHER_MACOS_BUNDLE_PLIST}")
set_target_properties(${PROJECT_NAME} PROPERTIES MACOSX_BUNDLE_INFO_PLIST "${SOLARUSLAUNCHER_MACOS_BUNDLE_PLIST}")
