set(CMAKE_MACOSX_RPATH ON)
set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
# set(CMAKE_INSTALL_RPATH "@executable_path/../Frameworks;@loader_path/../Frameworks")

# Add the bundle icon to the macOS bundle.
set(MACOSX_BUNDLE_ICON_FILE "solarus_launcher_icon.icns")
set(APP_ICON_MACOS "${CMAKE_CURRENT_SOURCE_DIR}/resources/app_icon/${MACOSX_BUNDLE_ICON_FILE}")
set_source_files_properties(${APP_ICON_MACOS} PROPERTIES MACOSX_PACKAGE_LOCATION "Resources")

set(MACOSX_DOCUMENT_ICON_FILE "macos_doc_icon.icns")
set(DOCUMENT_ICON_MACOS "${CMAKE_CURRENT_SOURCE_DIR}/resources/doc_icon/macos/${MACOSX_DOCUMENT_ICON_FILE}")
set_source_files_properties(${DOCUMENT_ICON_MACOS} PROPERTIES MACOSX_PACKAGE_LOCATION "Resources")

target_sources(${PROJECT_NAME} PRIVATE
  ${APP_ICON_MACOS}
  ${DOCUMENT_ICON_MACOS}
)

# macOS-specific settings.
set_target_properties(${PROJECT_NAME} PROPERTIES
  # ${BUNDLE_ID_OPTION}
  OUTPUT_NAME ${EXECUTABLE_NAME}
  MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
  MACOSX_BUNDLE_BUNDLE_NAME ${DISPLAY_NAME}
  MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
  MACOSX_BUNDLE_GUI_IDENTIFIER ${APP_IDENTIFIER}
  MACOSX_BUNDLE_COPYRIGHT ${APP_COPYRIGHT}
  MACOSX_BUNDLE_ICON_FILE ${MACOSX_BUNDLE_ICON_FILE}
  MACOSX_BUNDLE TRUE
  XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED OFF
  XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY ""
  XCODE_ATTRIBUTE_CODE_SIGN_STYLE "Manual"
  XCODE_ATTRIBUTE_CODE_SIGN_INJECT_BASE_ENTITLEMENTS OFF
  XCODE_ATTRIBUTE_OTHER_CODE_SIGN_FLAGS ""
  # INSTALL_RPATH "@executable_path/../Frameworks;@loader_path/../Frameworks"
)

# Add Info.plist to the macOS bundle only on macOS.
set(MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_BINARY_DIR}/Info.plist")
configure_file(
  "${CMAKE_CURRENT_SOURCE_DIR}/cmake/macOS/Info.plist.in"
  "${MACOSX_BUNDLE_INFO_PLIST}"
  @ONLY
)
target_sources(${PROJECT_NAME} PRIVATE "${MACOSX_BUNDLE_INFO_PLIST}")
set_target_properties(${PROJECT_NAME} PROPERTIES MACOSX_BUNDLE_INFO_PLIST "${MACOSX_BUNDLE_INFO_PLIST}")

# Set the deployment target for macOS.
# if(NOT CMAKE_OSX_DEPLOYMENT_TARGET)
  set(CMAKE_OSX_DEPLOYMENT_TARGET "13.6")
# endif()

set(BUNDLE_PATH "$<TARGET_BUNDLE_DIR:${PROJECT_NAME}>")
