# Source files.
set(solarus_quest_editor_SOURCES
  include/entities/block.h
  include/entities/chest.h
  include/entities/crystal.h
  include/entities/crystal_block.h
  include/entities/custom_entity.h
  include/entities/destination.h
  include/entities/destructible.h
  include/entities/door.h
  include/entities/dynamic_tile.h
  include/entities/enemy.h
  include/entities/entity_model.h
  include/entities/entity_traits.h
  include/entities/jumper.h
  include/entities/npc.h
  include/entities/pickable.h
  include/entities/sensor.h
  include/entities/separator.h
  include/entities/shop_treasure.h
  include/entities/stairs.h
  include/entities/stream.h
  include/entities/switch.h
  include/entities/teletransporter.h
  include/entities/tile.h
  include/entities/wall.h
  include/widgets/about_dialog.h
  include/widgets/border_set_selector.h
  include/widgets/border_set_tree_view.h
  include/widgets/change_border_set_id_dialog.h
  include/widgets/change_dialog_id_dialog.h
  include/widgets/change_file_info_dialog.h
  include/widgets/change_resource_id_dialog.h
  include/widgets/change_source_image_dialog.h
  include/widgets/change_string_key_dialog.h
  include/widgets/closable_tab_bar.h
  include/widgets/color_chooser.h
  include/widgets/dialog_properties_table.h
  include/widgets/dialogs_editor.h
  include/widgets/dialogs_tree_view.h
  include/widgets/edit_entity_dialog.h
  include/widgets/editor.h
  include/widgets/editor_tabs.h
  include/widgets/entity_item.h
  include/widgets/entity_selector.h
  include/widgets/enum_menus.h
  include/widgets/enum_menus.inl
  include/widgets/enum_selector.h
  include/widgets/enum_selector.inl
  include/widgets/external_script_dialog.h
  include/widgets/find_text_dialog.h
  include/widgets/get_animation_name_dialog.h
  include/widgets/gui_tools.h
  include/widgets/image_editor.h
  include/widgets/image_view.h
  include/widgets/import_dialog.h
  include/widgets/input_dialog_with_check_box.h
  include/widgets/lua_syntax_highlighter.h
  include/widgets/map_editor.h
  include/widgets/map_view.h
  include/widgets/map_scene.h
  include/widgets/main_window.h
  include/widgets/mouse_coordinates_tracking_tool.h
  include/widgets/music_chooser.h
  include/widgets/new_entity_user_property_dialog.h
  include/widgets/new_resource_element_dialog.h
  include/widgets/new_string_dialog.h
  include/widgets/pair_spin_box.h
  include/widgets/pan_tool.h
  include/widgets/pattern_chooser.h
  include/widgets/pattern_picker_dialog.h
  include/widgets/plain_text_edit.h
  include/widgets/quest_properties_editor.h
  include/widgets/quest_tree_view.h
  include/widgets/resource_model.h
  include/widgets/resource_selector.h
  include/widgets/settings_dialog.h
  include/widgets/shader_editor.h
  include/widgets/shader_previewer.h
  include/widgets/sound_chooser.h
  include/widgets/sprite_editor.h
  include/widgets/sprite_tree_view.h
  include/widgets/sprite_scene.h
  include/widgets/sprite_view.h
  include/widgets/sprite_previewer.h
  include/widgets/strings_editor.h
  include/widgets/strings_tree_view.h
  include/widgets/text_editor.h
  include/widgets/text_editor_widget.h
  include/widgets/tile_patterns_list_view.h
  include/widgets/tileset_editor.h
  include/widgets/tileset_scene.h
  include/widgets/tileset_view.h
  include/widgets/zoom_tool.h
  include/audio.h
  include/auto_tiler.h
  include/border_kind_traits.h
  include/border_set_model.h
  include/color.h
  include/dialogs_model.h
  include/editor_exception.h
  include/editor_settings.h
  include/enum_traits.h
  include/file_tools.h
  include/grid_style.h
  include/ground_traits.h
  include/indexed_string_tree.h
  include/map_model.h
  include/natural_comparator.h
  include/new_quest_builder.h
  include/obsolete_editor_exception.h
  include/obsolete_quest_exception.h
  include/pattern_repeat_mode_traits.h
  include/pattern_scrolling_traits.h
  include/pattern_separation.h
  include/pattern_separation_traits.h
  include/point.h
  include/quest.h
  include/quest_database.h
  include/quest_files_model.h
  include/quest_properties.h
  include/rectangle.h
  include/refactoring.h
  include/resize_mode.h
  include/size.h
  include/sprite_model.h
  include/shader_model.h
  include/shader_preview_mode.h
  include/shader_preview_mode_traits.h
  include/starting_location_mode_traits.h
  include/strings_model.h
  include/tileset_model.h
  include/transition_traits.h
  include/version.h
  include/view_settings.h
  src/entities/block.cpp
  src/entities/chest.cpp
  src/entities/crystal.cpp
  src/entities/crystal_block.cpp
  src/entities/custom_entity.cpp
  src/entities/destination.cpp
  src/entities/destructible.cpp
  src/entities/door.cpp
  src/entities/dynamic_tile.cpp
  src/entities/enemy.cpp
  src/entities/entity_model.cpp
  src/entities/entity_traits.cpp
  src/entities/jumper.cpp
  src/entities/npc.cpp
  src/entities/pickable.cpp
  src/entities/sensor.cpp
  src/entities/separator.cpp
  src/entities/shop_treasure.cpp
  src/entities/stairs.cpp
  src/entities/stream.cpp
  src/entities/switch.cpp
  src/entities/teletransporter.cpp
  src/entities/tile.cpp
  src/entities/wall.cpp
  src/widgets/about_dialog.cpp
  src/widgets/border_set_selector.cpp
  src/widgets/border_set_tree_view.cpp
  src/widgets/change_border_set_id_dialog.cpp
  src/widgets/change_dialog_id_dialog.cpp
  src/widgets/change_file_info_dialog.cpp
  src/widgets/change_resource_id_dialog.cpp
  src/widgets/change_source_image_dialog.cpp
  src/widgets/change_string_key_dialog.cpp
  src/widgets/closable_tab_bar.cpp
  src/widgets/color_chooser.cpp
  src/widgets/dialog_properties_table.cpp
  src/widgets/dialogs_editor.cpp
  src/widgets/dialogs_tree_view.cpp
  src/widgets/edit_entity_dialog.cpp
  src/widgets/editor.cpp
  src/widgets/editor_tabs.cpp
  src/widgets/entity_item.cpp
  src/widgets/entity_item.cpp
  src/widgets/entity_selector.cpp
  src/widgets/external_script_dialog.cpp
  src/widgets/find_text_dialog.cpp
  src/widgets/get_animation_name_dialog.cpp
  src/widgets/gui_tools.cpp
  src/widgets/image_editor.cpp
  src/widgets/image_view.cpp
  src/widgets/import_dialog.cpp
  src/widgets/input_dialog_with_check_box.cpp
  src/widgets/lua_syntax_highlighter.cpp
  src/widgets/main_window.cpp
  src/widgets/map_editor.cpp
  src/widgets/map_view.cpp
  src/widgets/map_scene.cpp
  src/widgets/mouse_coordinates_tracking_tool.cpp
  src/widgets/music_chooser.cpp
  src/widgets/new_entity_user_property_dialog.cpp
  src/widgets/new_resource_element_dialog.cpp
  src/widgets/new_string_dialog.cpp
  src/widgets/pair_spin_box.cpp
  src/widgets/pan_tool.cpp
  src/widgets/pattern_chooser.cpp
  src/widgets/pattern_picker_dialog.cpp
  src/widgets/quest_properties_editor.cpp
  src/widgets/quest_tree_view.cpp
  src/widgets/resource_model.cpp
  src/widgets/resource_selector.cpp
  src/widgets/settings_dialog.cpp
  src/widgets/shader_editor.cpp
  src/widgets/shader_previewer.cpp
  src/widgets/sound_chooser.cpp
  src/widgets/sprite_editor.cpp
  src/widgets/sprite_tree_view.cpp
  src/widgets/sprite_scene.cpp
  src/widgets/sprite_view.cpp
  src/widgets/sprite_previewer.cpp
  src/widgets/strings_editor.cpp
  src/widgets/strings_tree_view.cpp
  src/widgets/text_editor.cpp
  src/widgets/text_editor_widget.cpp
  src/widgets/tile_patterns_list_view.cpp
  src/widgets/tileset_editor.cpp
  src/widgets/tileset_scene.cpp
  src/widgets/tileset_view.cpp
  src/widgets/zoom_tool.cpp
  src/audio.cpp
  src/auto_tiler.cpp
  src/border_kind_traits.cpp
  src/border_set_model.cpp
  src/color.cpp
  src/dialogs_model.cpp
  src/editor_exception.cpp
  src/editor_settings.cpp
  src/file_tools.cpp
  src/grid_style.cpp
  src/ground_traits.cpp
  src/indexed_string_tree.cpp
  src/main.cpp
  src/map_model.cpp
  src/new_quest_builder.cpp
  src/obsolete_editor_exception.cpp
  src/obsolete_quest_exception.cpp
  src/pattern_repeat_mode_traits.cpp
  src/pattern_scrolling_traits.cpp
  src/pattern_separation_traits.cpp
  src/point.cpp
  src/quest.cpp
  src/quest_database.cpp
  src/quest_files_model.cpp
  src/quest_properties.cpp
  src/rectangle.cpp
  src/refactoring.cpp
  src/shader_model.cpp
  src/shader_preview_mode_traits.cpp
  src/size.cpp
  src/sprite_model.cpp
  src/starting_location_mode_traits.cpp
  src/strings_model.cpp
  src/tileset_model.cpp
  src/transition_traits.cpp
  src/view_settings.cpp
)
